development:
  adapter: postgresql
  database: mws-workflow-dev

test: &test
  adapter: postgresql
  database: mws-workflow-test

production:
  adapted: postgresql
  database: mws-workflow

cucumber:
  <<: *test
